/**
 * Generates src/lib/tag/font-metrics.ts: exact advance widths and ink bounds
 * for every character a decal can show, per Designer font, read from the
 * same TTF files the export converts to paths. The layout engine uses these
 * to keep text inside the print-safe area (it runs synchronously in the
 * browser, before any font file has loaded).
 *
 *   npx tsx scripts/gen-font-metrics.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import * as opentype from "opentype.js";

import { FONTS, FONT_LIST } from "../src/lib/tag/fonts";

// Decal text is uppercased; handles/usernames add digits and . _ - @; custom text can hold punctuation.
const CHARS = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).filter((c) => c === c.toUpperCase()).join("") + "·•—–’‘“”×°";

const out: Record<string, unknown> = {};
for (const f of FONT_LIST) {
  const buf = readFileSync(path.join(process.cwd(), "public", FONTS[f.id].file));
  const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
  const em = font.unitsPerEm;
  const r = (n: number) => Math.round((n / em) * 10000) / 10000;
  const glyphs: Record<string, [number, number, number, number, number]> = {};
  let fallback: [number, number, number, number, number] = [0, 0, 0, 0, 0];
  for (const ch of CHARS) {
    const g = font.charToGlyph(ch);
    if (!g || g.index === 0) continue;
    const bb = g.getBoundingBox();
    const hasInk = Number.isFinite(bb.x1) && !(bb.x1 === 0 && bb.x2 === 0 && bb.y1 === 0 && bb.y2 === 0);
    const m: [number, number, number, number, number] = [r(g.advanceWidth ?? 0), hasInk ? r(bb.x1) : 0, hasInk ? r(bb.x2) : 0, hasInk ? r(bb.y1) : 0, hasInk ? r(bb.y2) : 0];
    glyphs[ch] = m;
    fallback = [Math.max(fallback[0], m[0]), Math.min(fallback[1], m[1]), Math.max(fallback[2], m[2]), Math.min(fallback[3], m[3]), Math.max(fallback[4], m[4])];
  }
  out[f.id] = { glyphs, fallback };
}

writeFileSync(
  "src/lib/tag/font-metrics.ts",
  `/* Generated by scripts/gen-font-metrics.ts from /public/fonts. Do not edit. */
import type { FontId } from "./types";

/** Per character, in em: [advance, inkLeft, inkRight, inkBottom, inkTop] (y up, baseline 0). */
export type GlyphMetric = [number, number, number, number, number];

export const FONT_METRICS: Record<FontId, { glyphs: Record<string, GlyphMetric>; fallback: GlyphMetric }> = ${JSON.stringify(out)};
`,
);
console.log("wrote src/lib/tag/font-metrics.ts", CHARS.length, "chars x", FONT_LIST.length, "fonts");
