/**
 * Generates src/lib/tag/word-path.ts: the "BUILD / TAG" word used as a QR
 * center logo, traced to a single path from the shipped Barlow Condensed Bold
 * (OFL). Two stacked lines, TAG scaled up so both lines share one width.
 *
 *   pnpm tsx scripts/make-word-path.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import * as opentype from "opentype.js";

const ROOT = path.resolve(__dirname, "..");
const font = opentype.parse(readFileSync(path.join(ROOT, "public/fonts/BarlowCondensed-Bold.ttf")).buffer.slice(0) as ArrayBuffer);

const SIZE = 100;
const GAP = 8;
const opts = { kerning: true, letterSpacing: 0.02 };

const top = font.getPath("BUILD", 0, 0, SIZE, opts);
const topBox = top.getBoundingBox();
const topW = topBox.x2 - topBox.x1;

// TAG at whatever size makes it exactly as wide as BUILD.
const tagW1 = (() => {
  const b = font.getPath("TAG", 0, 0, SIZE, opts).getBoundingBox();
  return b.x2 - b.x1;
})();
const tagSize = (SIZE * topW) / tagW1;
const tag = font.getPath("TAG", 0, 0, tagSize, opts);
const tagBox = tag.getBoundingBox();

const topH = topBox.y2 - topBox.y1;
const tagH = tagBox.y2 - tagBox.y1;
const width = Math.max(topW, tagBox.x2 - tagBox.x1);
const height = topH + GAP + tagH;

// Place BUILD's ink at (0,0) and TAG below it, both left-aligned to x=0.
const move = (p: opentype.Path, dx: number, dy: number) => {
  for (const c of p.commands) {
    if ("x" in c && typeof c.x === "number") c.x += dx;
    if ("y" in c && typeof c.y === "number") c.y += dy;
    if ("x1" in c && typeof c.x1 === "number") c.x1 += dx;
    if ("y1" in c && typeof c.y1 === "number") c.y1 += dy;
    if ("x2" in c && typeof c.x2 === "number") c.x2 += dx;
    if ("y2" in c && typeof c.y2 === "number") c.y2 += dy;
  }
};
move(top, -topBox.x1, -topBox.y1);
move(tag, -tagBox.x1, -tagBox.y1 + topH + GAP);

const d = `${top.toPathData(2)} ${tag.toPathData(2)}`;
if (d.includes("NaN")) throw new Error("font outline produced NaN");

const out = `/**
 * "BUILD / TAG" word for the QR center, as one path (viewBox 0 0 ${width.toFixed(2)} ${height.toFixed(2)}).
 * Generated by scripts/make-word-path.ts from public/fonts/BarlowCondensed-Bold.ttf (OFL). Do not edit by hand.
 */
export const WORD_VIEWBOX = { width: ${width.toFixed(2)}, height: ${height.toFixed(2)} };
export const WORD_PATH =
  "${d}";
`;
writeFileSync(path.join(ROOT, "src/lib/tag/word-path.ts"), out);
console.log(`word-path.ts written: ${width.toFixed(1)} x ${height.toFixed(1)}, ${d.length} chars`);
