/**
 * Traces the supplied logos (white brush lettering on black) into single-path
 * SVGs, cropped tight to the lettering.
 *
 *   node scripts/trace-logos.mjs
 *
 * Sources (kept in the repo):
 *   public/brand/buildtags-wordmark.webp -> public/brand/logo{,-white,-dark}.svg   (site wordmark)
 *   public/brand/btag-mark.webp          -> src/lib/tag/brand-path.ts              (QR center logo + Designer mark)
 */
import { writeFileSync } from "node:fs";
import potrace from "potrace";
import sharp from "sharp";

const PAD = 8;

async function trace(src) {
  // White-on-black: trim the black border, then invert so the lettering is dark for potrace.
  const trimmed = await sharp(src).flatten({ background: "#000" }).grayscale().trim({ background: "#000000", threshold: 40 }).toBuffer({ resolveWithObject: true });
  const { width, height } = trimmed.info;
  const padded = await sharp(trimmed.data)
    .extend({ top: PAD, bottom: PAD, left: PAD, right: PAD, background: "#000" })
    .negate({ alpha: false })
    .png()
    .toBuffer();
  const svg = await new Promise((resolve, reject) =>
    potrace.trace(padded, { threshold: 128, turdSize: 12, optTolerance: 0.4, color: "#000" }, (err, out) => (err ? reject(err) : resolve(out))),
  );
  const d = /<path[^>]*\sd="([^"]+)"/.exec(svg)[1].replace(/\s+/g, " ").trim();
  return { d, width: width + PAD * 2, height: height + PAD * 2 };
}

const site = await trace("public/brand/buildtags-wordmark.webp");
const svgFor = (fill) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${site.width} ${site.height}"><path d="${site.d}" fill="${fill}" fill-rule="evenodd"/></svg>\n`;
writeFileSync("public/brand/logo.svg", svgFor("#000"));
writeFileSync("public/brand/logo-dark.svg", svgFor("#0a0a0b"));
writeFileSync("public/brand/logo-white.svg", svgFor("#fff"));
console.log("site wordmark", site.width, "x", site.height, site.d.length, "chars");

const mark = await trace("public/brand/btag-mark.webp");
writeFileSync(
  "src/lib/tag/brand-path.ts",
  `/** Traced Btag mark (single path, viewBox 0 0 ${mark.width} ${mark.height}). Generated by scripts/trace-logos.mjs from public/brand/btag-mark.webp. */
export const BRAND_VIEWBOX = { width: ${mark.width}, height: ${mark.height} };
export const BRAND_PATH =
  ${JSON.stringify(mark.d)};
`,
);
console.log("qr mark", mark.width, "x", mark.height, mark.d.length, "chars");
